language: go
sudo: required
install: true
os:
  - linux
go:
  - 1.9.2
  - master
env:
  global:
    - GO_FOR_RELEASE=1.9
  matrix:
    - GOARCH=amd64
    - GOARCH=386
matrix:
  allow_failures:
    - go: master
script:
  - go test -x ./...
after_success:
  - if [ -n "$TRAVIS_TAG" ]; then curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push.sh | PACKAGE_NAME=deploy-agent bash; fi
